### ISSUE TITLE
Error on make 

### ISSUE THREAD

**Issue by mkleyman** [Kingsford-Group/scallop#12]
Hi I making installing scallop form source on Centos 6.5 with GCC 5.4.0 and I get the following error when I run make 

gtf.cc: In member function 'int gtf::add_edges(splice_graph&)':
gtf.cc:88:47: error: call of overloaded 'distance(SIMI, SIMI&)' is ambiguous
     int uu = distance((SIMI)(imap.begin()), it) + 1;
                                               ^
In file included from /home/mkleyman/boost_1_68_0/boost/range/distance.hpp:18:0,
                 from /home/mkleyman/boost_1_68_0/boost/range/functions.hpp:21,
                 from /home/mkleyman/boost_1_68_0/boost/range/iterator_range_core.hpp:38,
                 from /home/mkleyman/boost_1_68_0/boost/range/iterator_range.hpp:13,
                 from /home/mkleyman/boost_1_68_0/boost/icl/concept/interval_associator.hpp:11,
                 from /home/mkleyman/boost_1_68_0/boost/icl/associative_interval_container.hpp:18,
                 from /home/mkleyman/boost_1_68_0/boost/icl/interval_base_set.hpp:24,
                 from /home/mkleyman/boost_1_68_0/boost/icl/interval_set.hpp:14,
                 from /home/mkleyman/boost_1_68_0/boost/icl/interval_map.hpp:13,
                 from interval_map.h:11,
                 from gtf.h:14,
                 from gtf.cc:8:
/home/mkleyman/boost_1_68_0/boost/iterator/distance.hpp:49:9: note: candidate: typename boost::iterators::iterator_difference<Iterator>::type boost::iterators::distance_adl_barrier::distance(SinglePassIterator, SinglePassIterator) [with SinglePassIterator = std::_Rb_tree_const_iterator<std::pair<const boost::icl::right_open_interval<int>, int> >; typename boost::iterators::iterator_difference<Iterator>::type = long int]
         distance(SinglePassIterator first, SinglePassIterator last)
         ^
In file included from /opt/gcc/5.4.0/include/c++/5.4.0/bits/stl_algobase.h:66:0,
                 from /opt/gcc/5.4.0/include/c++/5.4.0/algorithm:61,
                 from gtf.cc:7:
/opt/gcc/5.4.0/include/c++/5.4.0/bits/stl_iterator_base_funcs.h:114:5: note: candidate: typename std::iterator_traits<_Iterator>::difference_type std::distance(_InputIterator, _InputIterator) [with _InputIterator = std::_Rb_tree_const_iterator<std::pair<const boost::icl::right_open_interval<int>, int> >; typename std::iterator_traits<_Iterator>::difference_type = long int]
     distance(_InputIterator __first, _InputIterator __last)
     ^
make[2]: *** [scallop-gtf.o] Error 1

**Comment by shaomingfu** [comment]
Hi Michael,

Could you try boost 1.60 instead of the latest 1.68? On my machine it works well with 1.60 but the same error occurs when I switch to 1.68.

I am digging into the source code to figure out what happens with boost 1.68 and will let you know.

Thanks,
Mingfu
