### ISSUE TITLE
Bioconda package?

### ISSUE THREAD

**Issue by sschmeier** [Kingsford-Group/scallop#14]
Hi there,

I would love to be able to integrate it in our pipelines but we need a bioconda package for it. Any plans to providing this? 

Thank you very much,

    Sebastian

**Comment by shaomingfu** [comment]
Hi Sebastian,

We are working on that now; it is not as easy as we thought, since the Clp library dependency is hard to incorporate.

Best,
Mingfu

**Comment by sschmeier** [comment]
How about a docker container on dockerhub for now?

**Comment by fgypas** [comment]
Hi.

Any news on packaging the tool for bioconda?

Foivos

**Comment by shaomingfu** [comment]
@fgypas @sschmeier 

Hi there,

The latest release of Scallop (v0.10.4) is now available in bioconda: https://anaconda.org/bioconda/scallop (The macOS version will be available soon, as the queue of building OSX packages is long now).

Thanks,
Mingfu
