### ISSUE TITLE
Compiling Scallop-LR v0.9.1: are files missing from the archive?

### ISSUE THREAD

**Issue by andreaswallberg** [Kingsford-Group/scallop#17]
Dear developers,

I am trying to compile Scallop-LR on Ubuntu 16.04 using scallop-lr-0.9.1.tar.gz (73c310d). I get to his point:

`make[2]: Entering directory '/vaults/vault3/andreasw/devel/scallop-lr/scallop-lr-0.9.1/src'
g++ -DHAVE_CONFIG_H -I. -I..  -std=c++11 -I../lib/gtf -I../lib/graph -I../lib/util   -I/usr/include/coin//include/coin -g -O2 -MT scallop-assembler.o -MD -MP -MF .deps/scallop-assembler.Tpo -c -o scallop-assembler.o `test -f 'assembler.cc' || echo './'`assembler.cc
assembler.cc:18:24: fatal error: quantifier.h: No such file or directory`

quantifier.h is missing from this archive. Such a header and cc file exists in scallop-isoseq-v0.9.1.tar.gz. Should this file also exist in in scallop-lr-0.9.1.tar.gz?

I copied it over from scallop-isoseq-v0.9.1.tar.gz and restarted the compilation. This takes me a little further:

`g++ -DHAVE_CONFIG_H -I. -I..  -std=c++11 -I../lib/gtf -I../lib/graph -I../lib/util   -I/usr/include/coin//include/coin -g -O2 -MT scallop-assembler.o -MD -MP -MF .deps/scallop-assembler.Tpo -c -o scallop-assembler.o `test -f 'assembler.cc' || echo './'`assembler.cc
In file included from assembler.cc:19:0:
quantifier.h:12:23: fatal error: super_hit.h: No such file or directory`

Copying also super_hit.h from scallop-isoseq-v0.9.1.tar.gz over to scallop-lr-0.9.1 allows me to complete and run scallop. However, the runtime in scallop-lr-0.9.1 identifies itself as "Scallop isoseq-v0.9.1" when I start it.

Now I wonder which of these two archives should actually be compiled, how they differ from a computational point of view (if at all) and if my solution to the missing files was valid.

Many thanks!

**Comment by shaomingfu** [comment]
Hi Andreas,

Thank you for using Scallop-LR and your feedback!

quantifier.h is not used in Scallop-LR anymore. You can comment out line 19 of assembler.cc (i.e., #include "quantifier.h"), and everything should be fine then. This was a bug and we have fixed that; now the source code released should work: https://github.com/Kingsford-Group/scallop/releases/download/isoseq-v0.9.1/scallop-lr-0.9.1.tar.gz

Thanks,
Mingfu
