### ISSUE TITLE
scallop parameters min_router_count

### ISSUE THREAD

**Issue by azyro** [Kingsford-Group/scallop#18]
Dear developers,
Recently, I am using scallopadvising for  choosing input-specific parameter values for reference-based transcript assembly. From the training result, I found that the scallop parameters `min_router_count` can change the  assemble result apparently. But I can't find the meaning of the parameter .Can you tell me the meaning of the parameter?

**Comment by shaomingfu** [comment]
min_router_count represents the minimum coverage of each phasing path. More specifically, phasing paths are extracted from reads that span more than two vertices in the splice graph, and the coverage of each phasing path is defined as the number of reads that generate the same phasing path. Phasing paths with coverage lower than min_router_count will be filtered out.
