### ISSUE TITLE
How to limit the length of assembled transcripts

### ISSUE THREAD

**Issue by azyro** [Kingsford-Group/scallop#19]
Hi,
   After I use scallop assemble the transcripts of plant, I load the gtf file into IGV, and compared with the reference genome annotation. I found many error is artifactual fusion/chimeric transcripts
that chain together multiple genes. This type of transcript is very long，I want to ask if scallop have any parameters to limit the assembled transcript length?

All best wishes,
xu

**Comment by shaomingfu** [comment]
Hi Xu,

Thank you for using Scallop and providing us feedback!

There is no such option within Scallop. But you can use a postprocessing procedure to select transcripts satisfying certain length range. We just released a new version of rnaseqtools (https://github.com/Kingsford-Group/rnaseqtools), in which such function is provided (please check out the README page; gtfformat module).

Best,
Mingfu
