### ISSUE TITLE
gtfcuff compile error

### ISSUE THREAD

**Issue by LegebekeJ** [Kingsford-Group/scallop#22]
Could anyone give some assistance to a complete beginner?

I'm following the steps in the Quantification by Combining Scallop and Salmon instructions. I installed all tools on a conda environment except gtfcuff (couldn't find it on anaconda.org). So I downloaded the tool (https://github.com/Kingsford-Group/rnaseqtools) myself and tried to compile it. However, I'm getting the following and I don't know if everything is going allright?

The ./configure --prefix=/path/to/your/install/folder part seemed to work but for the make part I get:

(base) [jl2e19@cyan03 gtfcuff]$ make
make  all-recursive
make[1]: Entering directory `/home/jl2e19/gtfcuff'
Making all in lib
make[2]: Entering directory `/home/jl2e19/gtfcuff/lib'
Making all in util
make[3]: Entering directory `/home/jl2e19/gtfcuff/lib/util'
g++ -DHAVE_CONFIG_H -I. -I../.././rnaseqtools-1.0.3/lib/util -I../..     -g -O2 -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o ../.././rnaseqtools-1.0.3/lib/util/util.cc
mv -f .deps/util.Tpo .deps/util.Po
rm -f libutil.a
ar cru libutil.a util.o
ranlib libutil.a
make[3]: Leaving directory `/home/jl2e19/gtfcuff/lib/util'
Making all in gtf
make[3]: Entering directory `/home/jl2e19/gtfcuff/lib/gtf'
g++ -DHAVE_CONFIG_H -I. -I../.././rnaseqtools-1.0.3/lib/gtf -I../..  -I../util   -g -O2 -MT libgtf_a-item.o -MD -MP -MF .deps/libgtf_a-item.Tpo -c -o libgtf_a-item.o `test -f 'item.cc' || echo '../.././rnaseqtools-1.0.3/lib/gtf/'`item.cc
mv -f .deps/libgtf_a-item.Tpo .deps/libgtf_a-item.Po
g++ -DHAVE_CONFIG_H -I. -I../.././rnaseqtools-1.0.3/lib/gtf -I../..  -I../util   -g -O2 -MT libgtf_a-transcript.o -MD -MP -MF .deps/libgtf_a-transcript.Tpo -c -o libgtf_a-transcript.o `test -f 'transcript.cc' || echo '../.././rnaseqtools-1.0.3/lib/gtf/'`transcript.cc
mv -f .deps/libgtf_a-transcript.Tpo .deps/libgtf_a-transcript.Po
g++ -DHAVE_CONFIG_H -I. -I../.././rnaseqtools-1.0.3/lib/gtf -I../..  -I../util   -g -O2 -MT libgtf_a-gene.o -MD -MP -MF .deps/libgtf_a-gene.Tpo -c -o libgtf_a-gene.o `test -f 'gene.cc' || echo '../.././rnaseqtools-1.0.3/lib/gtf/'`gene.cc
mv -f .deps/libgtf_a-gene.Tpo .deps/libgtf_a-gene.Po
g++ -DHAVE_CONFIG_H -I. -I../.././rnaseqtools-1.0.3/lib/gtf -I../..  -I../util   -g -O2 -MT libgtf_a-genome.o -MD -MP -MF .deps/libgtf_a-genome.Tpo -c -o libgtf_a-genome.o `test -f 'genome.cc' || echo '../.././rnaseqtools-1.0.3/lib/gtf/'`genome.cc
../.././rnaseqtools-1.0.3/lib/gtf/genome.cc:13:18: error: util.h: No such file or directory
../.././rnaseqtools-1.0.3/lib/gtf/genome.cc: In member function 'const gene* genome::locate_gene(const std::string&, const PI32&) const':
../.././rnaseqtools-1.0.3/lib/gtf/genome.cc:118: error: 'compute_overlap' was not declared in this scope
make[3]: *** [libgtf_a-genome.o] Error 1
make[3]: Leaving directory `/home/jl2e19/gtfcuff/lib/gtf'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/jl2e19/gtfcuff/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/jl2e19/gtfcuff'
make: *** [all] Error 2

And for makeinstall I get:

Making install in lib
make[1]: Entering directory `/home/jl2e19/gtfcuff/lib'
Making install in util
make[2]: Entering directory `/home/jl2e19/gtfcuff/lib/util'
make[3]: Entering directory `/home/jl2e19/gtfcuff/lib/util'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/home/jl2e19/gtfcuff/lib/util'
make[2]: Leaving directory `/home/jl2e19/gtfcuff/lib/util'
Making install in gtf
make[2]: Entering directory `/home/jl2e19/gtfcuff/lib/gtf'
g++ -DHAVE_CONFIG_H -I. -I../.././rnaseqtools-1.0.3/lib/gtf -I../..  -I../util   -g -O2 -MT libgtf_a-genome.o -MD -MP -MF .deps/libgtf_a-genome.Tpo -c -o libgtf_a-genome.o `test -f 'genome.cc' || echo '../.././rnaseqtools-1.0.3/lib/gtf/'`genome.cc
../.././rnaseqtools-1.0.3/lib/gtf/genome.cc:13:18: error: util.h: No such file or directory
../.././rnaseqtools-1.0.3/lib/gtf/genome.cc: In member function 'const gene* genome::locate_gene(const std::string&, const PI32&) const':
../.././rnaseqtools-1.0.3/lib/gtf/genome.cc:118: error: 'compute_overlap' was not declared in this scope
make[2]: *** [libgtf_a-genome.o] Error 1
make[2]: Leaving directory `/home/jl2e19/gtfcuff/lib/gtf'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/jl2e19/gtfcuff/lib'
make: *** [install-recursive] Error 1

So I am currently kinda stuck at step 4. Could anyone give me some advice on how to get step 4 working? I would love to use this tool. Used STAR for alignment btw and have SALMON up and running.

Much appreciated and thanks in advance!

**Comment by shaomingfu** [comment]
Could you try the latest release we just made (https://github.com/Kingsford-Group/rnaseqtools/releases/tag/v1.0.4)? Thanks for using our tool!

Best,
Mingfu

**Comment by LegebekeJ** [comment]
Awesome, now we're cooking with gas! Everything is up and running. Thanks for your help in generating the new release, much appreciated!
