### ISSUE TITLE
deal with multiple bam file ?

### ISSUE THREAD

**Issue by shenweima** [Kingsford-Group/scallop#3]
Can scallop deal with multiple bam file ?
`scallop -i SRR4734844.sorted.bam -i SRR4734845.sorted.bam -o 1.gtf`

**Comment by shaomingfu** [comment]
Current version of Scallop does not support multiple bam files. You need to merge them before running Scallop using tools such as samtools. Notice that the merged bam file needs to be sorted before piping to Scallop. You might also consider first assembling each of the bam file using Scallop and then merge the predicted transcripts.
