### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xizhesun** [Kingsford-Group/scallop#30]
Hi Mingfu,

I use Scallop with --library_type unstranded and make a GTF file. The question is that why the GTF file have strand information? Thank you!

All Best,
Xizhe

**Comment by shaomingfu** [comment]
Hi Xizhe, 

Sorry for the late response. The strandness information comes from alignment: the aligner will determine the strangeness of a read by examining if the donor/acceptor sites of a junction (if any) in this read are canonical splice sites (i.e., GT/AG). Such strandness information of reads will be encoded in the alignment (mostly in the XS tag in bam/sam format) and they will be used by Scallop to determine the strandness of the resulting transcript.

Best,
Mingfu
