### ISSUE TITLE
conda installs 0.10.4 not 0.10.5 for scallop

### ISSUE THREAD

**Issue by sanyalab** [Kingsford-Group/scallop#32]
Hello,

Conda installs the 0.10.4 version of scallop, when `conda install -c bioconda scallop` is specified. Explicitly specifying `0.10.5` leads to package conflicts and errors. 

Scallop (0.10.4) works with boost-cpp (v1.70.0) and htslib (v1.9). Is there going to be an update?

Thanks
Abhijit

**Comment by shaomingfu** [comment]
Hello,

0.10.5 is available at conda; see: https://anaconda.org/bioconda/scallop

Can you try "conda update scallop"? This updates it to 0.10.5 on my end.

Thanks,
Mingfu
