### ISSUE TITLE
Plant specific scallop parameters

### ISSUE THREAD

**Issue by sanyalab** [Kingsford-Group/scallop#33]
Hello,

This is not an issue, but I wanted to know if there is any parameter in scallop to

1) Specify min and max intron sizes
2) Provide a GTF/GFF3 file from a trusted annotation as guide for transcriptome assembly OR provide at least provide splice site file

Thanks
Abhijit

**Comment by shaomingfu** [comment]
Hi Abhijit,

1, No. You may consider writing a script that post-processes the assembled transcripts (in .gtf format) to filter out ones that don't meet the min/max intron sizes you defined.
2, Again no. We strongly suggest you provide trusted annotation to aligners (for examples, both STAR and HISAT2 accept such annotations to improve alignment, as far as we know). Scallop uses (and trusts) the splices in the alignment so improved alignment will definitely improve the assembly accuracy.

Thanks for using Scallop,
Mingfu

**Comment by sanyalab** [comment]
Ok. Thank you for the input. Yes both STAR and HISAT2 have the option to provide splice sites. Just out of curiosity, and probably off topic, generally there is no need to provide the splice sites to transcriptome assemblers if aligners use them to build the genome database. Will this be correct statement?
