### ISSUE TITLE
combined BAM files vs multiple BAM files

### ISSUE THREAD

**Issue by gianfilippo** [Kingsford-Group/scallop#4]
Hi,

I would like to ask an 'old' question. 

Would you combine multiple BAM files into one single BAM at very high sequencing depth and run Scallop ? can Scallop handle it and benefit from it ? 

Thanks

**Comment by shaomingfu** [comment]
Current version of Scallop does not support multiple bam files. You need to merge them before running Scallop using tools such as samtools. Notice that the merged bam file needs to be sorted before piping to Scallop. Scallop definitely benefits from high sequencing depth.

**Comment by gianfilippo** [comment]
thanks!
