### ISSUE TITLE
Compatibility with TACO

### ISSUE THREAD

**Issue by jxf413** [Kingsford-Group/scallop#6]
Hi there!

I was wondering if counting-type functionality may eventually be added to Scallop for use with the new transcript meta-assembly tool TACO (https://tacorna.github.io/). From what I'm seeing, TACO is looking for attributes in the GTF file (TPM/FPKM/RPKM) which Cufflinks and StringTie provide, but Scallop currently does not. I think that combining Scallop and Taco could make for really rock-solid assemblies.

In the interim, would it be suggestible to combine .BAM files and use Scallop to generate a full experiment-wide assembly (before merging with a reference), or would it be more sensible to make a series of Scallop assemblies and merge with something like gffmerge? 

EDIT: Scallop does provide count estimation, I just don't have working eyes

**Comment by shaomingfu** [comment]
Hi,
Scallop provides the RPKM value for each of the predicted transcript.
If the bam files are highly related (e.g., from the same experiment), then I would suggest merging them before running Scallop.

**Comment by jxf413** [comment]
How embarrassing! Whoops, thanks so much!

**Comment by shaomingfu** [comment]
Thanks for your interests in using Scallop!
