### ISSUE TITLE
--preview and --library_type

### ISSUE THREAD

**Issue by lcscs12345** [Kingsford-Group/scallop#7]
Hi Mingfu,

Thank you for creating Scallop. It is fast and safe me a lot of time when testing my pipeline.

I've tested --preview on different library types - strand specific single-end, paird-end fr-firststrand and fr-secondstrand. However, they were inferred as unstranded. In contrast, they were inferred as stranded by infer_experiment.py ( [http://rseqc.sourceforge.net/#infer-experiment-py](url)). I'm analyzing publicly available data so this is essential.

FYI as far as I understand the output from infer_experiment.py,
1++,1--,2+-,2-+ value dominates then its fr-secondstrand whereas
1+-,1-+,2++,2-- value dominates then its fr-firststrand

**Comment by shaomingfu** [comment]
Hi Chun Shen,

Thank you for your feedback and your interests in using our tool!

Scallop uses 'XS' tag in the alignment files to detect library types. So please first check whether the alignment file contains such tags. If no XS tag is given, you should specify the library type to Scallop through "--library_type" parameter (for example, the library_type can be obtained through running infer_experiment.py).

Best,
Mingfu

**Comment by lcscs12345** [comment]
Sorry my bad. Didn't read the manual carefully. It might be useful to prompt this message after --preview.
