### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error'   what():  basic_string::_S_construct NULL not valid

### ISSUE THREAD

**Issue by haidudu** [Kingsford-Group/scallop#8]
HI,
I have 2 questions
1:
This is my command
/biosoft/scallop-0.10.2_linux_x86_64/scallop -i huahuasingle_unmapped.bam -o scallop.gtf --library_type &
and it turned: terminate called after throwing an instance of 'std::logic_error'   what():  basic_string::_S_construct NULL not valid
2: Is there any command about "threads option" to add CPUs for faster results?
                                                                                                                           Thanks for your attention

**Comment by shaomingfu** [comment]
Hi,

1. If you use "--library_type" in the command line, the specific library type must be given after that, for example, "--library_type first".

2, Current version of scallop does not support multiple-threading. We will add such feature in the future releases.

Best,
Mingfu

**Comment by haidudu** [comment]
i used the command :
 "command line: /biosoft/scallop-0.10.2_linux_x86_64/scallop -i huahuasingle_unmapped.bam -o huaunstranded.gtf --preview "
then it turned:
 "preview: reads = 0, single = 0, paired = 0, spliced reads = 0, first = 0, second = 0, inferred library_type = unstranded, given library_type = empty"
ps:
 the "huahuasingle_unmapped.bam" is the unmapping sequence that I used bowtie2 aligned paired files to  reference genome and then used samtools extracted  from the sam file. 

so  should i use  "--library_type unstranded" ?
command line: /biosoft/scallop-0.10.2_linux_x86_64/scallop -i huahuasingle_unmapped.bam -o huaunstranded.gtf --library_type unstranded
but i still have no result :-rw-r--r-- 1 rhizoctonia Rhizoctonia           0 Mar 13 01:46 huaunstranded.gtf

THANKS
